name: Build RMM Client
on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Install Missing Parts
        run: |
          vcpkg install nlohmann-json spdlog toml11 --triplet x64-windows

      - name: Build with CMake
        shell: pwsh
        run: |
          cd client
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows "-DPython_ROOT_DIR=$env:Python_ROOT_DIR"
          cmake --build . --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Havoc-Client-Windows
          path: client/build/Release/Havoc.exe
