name: Build RMM Client
on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Havoc works best with 3.10

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Install Dependencies via vcpkg
        run: |
          vcpkg install nlohmann-json spdlog toml11

      - name: Build with CMake
        run: |
          cd Client
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Havoc-Client-Windows
          path: Client/build/Release/Havoc.exe
